# Generated by Django 6.0.4 on 2026-04-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("docente", models.CharField(max_length=200)),
                ("link_docente", models.URLField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
