# Generated by Django 6.0.4 on 2026-04-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("website", models.URLField()),
                ("logo", models.ImageField(upload_to="tecnologias/")),
                ("nivel", models.IntegerField(help_text="Nível de 1 a 5")),
            ],
        ),
    ]
