# Generated by Django 6.0.4 on 2026-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_formacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(max_length=200)),
                ("orientador", models.CharField(max_length=200)),
                ("curso", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField(blank=True)),
                ("palavras_chave", models.TextField(blank=True)),
                ("areas", models.TextField(blank=True)),
                ("tecnologias", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("imagem", models.URLField(blank=True)),
                ("pdf", models.URLField(blank=True)),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
