# Generated by Django 6.0.4 on 2026-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienciaProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estagio", "Estágio"),
                            ("part_time", "Part-time"),
                            ("full_time", "Full-time"),
                        ],
                        max_length=50,
                    ),
                ),
                ("localizacao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField()),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, help_text="Marcar experiências mais importantes"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="experiencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
        ),
    ]
