# Generated by Django 6.0.4 on 2026-04-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_experienciaprofissional"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="ects",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="horas_contacto",
            field=models.IntegerField(default=0),
        ),
    ]
