# Generated by Django 6.0.4 on 2026-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_unidadecurricular_ects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "entidade_relacionada",
                    models.CharField(
                        help_text="Ex: Projeto, UC, Tecnologia, TFC, etc.",
                        max_length=100,
                    ),
                ),
                ("descricao_decisoes", models.TextField()),
                ("erros_encontrados", models.TextField(blank=True)),
                ("correcoes_aplicadas", models.TextField(blank=True)),
                ("justificacao_modelacao", models.TextField()),
                (
                    "uso_ia",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do uso de IA no desenvolvimento",
                    ),
                ),
                ("data_registo", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
