# Generated by Django 6.0.5 on 2026-05-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_makingof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(),
        ),
    ]
